name: Dependabot Auto Merge

on:
  pull_request:
    branches:
      - develop

jobs:
  DependabotAutoMerge:
    uses: IsyFact/isy-github-actions-templates/.github/workflows/dependabot_auto_merge_template.yml@v1.6.0
    secrets:
      DEPENDABOT_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}
