name: Dependency Review
on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  DependencyReview:
    uses: IsyFact/isy-github-actions-templates/.github/workflows/dependency_review_template.yml@v1.6.0
