name: Maven Release
on:
  release:
    types: [released]

jobs:
  Build:
    uses: IsyFact/isy-github-actions-templates/.github/workflows/maven_build_template.yml@v1.6.0
    with:
      jdk-version: 21
      version: ${{ github.ref_name }}
      sonar-skip: true

  DeployMavenCentral:
    needs: [ Build ]
    uses: IsyFact/isy-github-actions-templates/.github/workflows/maven_deploy_template.yml@v1.6.0
    with:
      jdk-version: 21
      version: ${{ github.ref_name }}
      maven-opts: '-P centralRelease'
      deploy-server-id: ossrh
      sbom: true
      sign: true
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      DEPLOY_SERVER_USER_NAME: ${{ secrets.MAVEN_CENTRAL_USER_NAME }}
      DEPLOY_SERVER_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}

  DependencyMonitor:
    needs: [ DeployMavenCentral ]
    uses: IsyFact/isy-github-actions-templates/.github/workflows/maven_dependency_scan_template.yml@v1.6.0
    with:
      jdk-version: 21
      snyk-reference: ${{ github.ref_name }}
      snyk-organization: ${{ vars.SNYK_ORG_ID }}
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
