# Maven Build: Compile, Test, SonarCloudScan
name: Maven Build

on:
  push:
    branches:
      - main
      - develop
      - release/**
      - hotfix/**
      - feature/**
      - bugfix/**
    paths:
      - .github/**
      - src/**
      - pom.xml
  workflow_dispatch:

jobs:
  Version:
    uses: IsyFact/isy-github-actions-templates/.github/workflows/next_version.yml@v1.6.0
    with:
      next-version: 4.0.0
      calculate-rc: ${{ startsWith(github.ref, 'refs/heads/release/') }}

  MavenBuild:
    needs: [ Version ]
    uses: IsyFact/isy-github-actions-templates/.github/workflows/maven_build_template.yml@v1.6.0
    with:
      version: ${{ needs.Version.outputs.next-version }}
      jdk-version: 21
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
