name: Maven Dependency Scan
on:
  push:
    branches:
      - develop
      - release/**
    paths:
      - pom.xml

jobs:
  SnykScan:
    uses: IsyFact/isy-github-actions-templates/.github/workflows/maven_dependency_scan_template.yml@v1.6.0
    with:
      jdk-version: 21
      snyk-reference: ${{ github.ref_name }}
      snyk-organization: ${{ vars.SNYK_ORG_ID }}
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
